language: node_js
cache: yarn
node_js:
- '6'
matrix:
  include:
    - node_js: '6'
      script: yarn test
    - node_js: '7'
      script: yarn test
git:
  depth: 10
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
